services:
  drupal:
    image: "${PROJECT_NAME}_frankenphp"
    container_name: "${PROJECT_NAME}_frankenphp"
    build:
      context: .
      dockerfile: drupal.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/public/modules
      - /app/public/profiles
      - /app/public/themes
      - /app/public/sites
    depends_on:
      - postgres
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT}
    restart: always

  postgres:
    container_name: "${PROJECT_NAME}_postgres"
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always

  adminer:
    image: adminer
    container_name: "${PROJECT_NAME}_adminer"
    restart: always
    ports:
      - 1400:8080



