_core:
  default_config_hash: M4problxHEyzVhSfwhvSCpPWr50u9ygH6lzjDVbGTDg
fe_uri: 'http://localhost:5173/'
fe_uri_custom: true
fe_uri_suffix: /password-reset/
name_mail_subject: 'Your username for [site:name]'
name_mail_body: "Your username for [site:name] is:\r\n\r\n[user:account-name]\r\n\r\n-- [site:name] team"
reset_mail_subject: 'Demande de réinitialisation de mot de passe pour votre compte sur [site:name]'
reset_mail_body: "[user:display-name],\r\n\r\nUne demande de réinitialisation du mot de passe pour votre compte a été effectuée sur [site:name].\r\n\r\nVous pouvez maintenant vous connecter en cliquant sur ce lien ou en le copiant et en le collant dans votre navigateur :\r\n\r\n[rest_password_reset:login_link]\r\n\r\nCe lien ne peut être utilisé qu'une seule fois pour vous connecter et vous dirigera vers une page où vous pourrez définir votre mot de passe. Il expire après un jour et rien ne se passera s'il n'est pas utilisé.\r\n\r\n--  [site:name] team"
