_core:
  default_config_hash: KsPFWSp6mgXIQgjBJEShfKUGn6VLRlbpIJ2EysXvXWM
access_token_expiration: 1209600
authorization_code_expiration: 1209600
refresh_token_expiration: 1209600
token_cron_batch_size: 0
public_key: ../config/jwt/public.key
private_key: ../config/jwt/private.key
remember_clients: true
use_implicit: false
disable_openid_connect: false
