_core:
  default_config_hash: HENvUIeX6xNPGRB1w3z6rT9a71LM_hKXATF6XrM9WvM
smtp_on: true
smtp_host: smtp-relay.gmail.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: vadly
smtp_password: vadly
smtp_from: vadly@applize.io
smtp_fromname: Vesper
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: vadly427@gmail.com
smtp_reroute_address: vadly427@gmail.com
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: true
